### PR TITLE
Password protected retros

### LINKED ISSUE #40: Add password protection to retros
How passwords work in the API, error codes, etc. are all documented in https://github.com/retro-tool/retro-tool-api/pull/18.

Acceptance criteria

- Any user with access to the retro can update the password
- When a connected user receives an unauthorized error (via query or via subscriptions), they should be prompted to enter the password
- Retros without password should still work just fine the same as now

Discussion started in https://github.com/retro-tool/retro-tool/issues/6

### PR DESCRIPTION
**Pull request by marciobarrios**
This PR is adding the needed UI to make private retros, that means basically adding a password, updating and removing it.

For now a password is stored in sessionStorage so if the user closes the tab it will need to write again the password. It's stored as it is without any transformation, I think it's ok but I'm open to consider hashing the string.

Please test this feature in several cases as the changes are quite big and we don't want to break the existing behavior.

I also fixed/tweaked some other minor things like landing pages texts, export layout or breadcrumb size.

Fixes https://github.com/retro-tool/retro-tool/issues/40

## To do
- [x]  Possibility to remove a password (the code in the FE is commented, it just needs this issue from BE: https://github.com/retro-tool/retro-tool/issues/59)

## Video
https://user-images.githubusercontent.com/47644/111871813-533f0d80-898c-11eb-880a-d5566d98865c.mp4

### CODE REVIEW

**Comment by marciobarrios** [comment]
@uesteibar I just realized that when you finish a password protected retro and start a new linked retro the password is gone, probably we should keep it right?

**Comment by uesteibar** [comment]
@marciobarrios you mean to copy the password to the new retro?

**Comment by marciobarrios** [comment]
@uesteibar yes, but I'm not 100% sure if it's needed/desired. So we can go without this feature and wait for feedback.

**Comment by uesteibar** [comment]
@marciobarrios that sounds sensible to me actually.

@rudeayelo @atrzaska wdyt about passing passwords on to the next linked retro?

**Comment by atrzaska** [comment]
@uesteibar @marciobarrios that sounds like a good idea. I would make sure to inform the user about this behaviour when creating next retro.

**Comment by rudeayelo** [comment]
Agree with @atrzaska, I think people will mostly want to keep a series of retros protected, but for sure I'd let them know somehow. Maybe @iamsilesc has an opinion here too.

**Comment by marciobarrios** [comment]
@atrzaska @rudeayelo I also think this will be the expected behavior (password remains in a linked retro), and probably the only needed place to inform the user about this feature is in the dialog when the user can set/update/remove a password.

**Comment by uesteibar** [comment]
I added https://github.com/retro-tool/retro-tool/issues/60 for the BE and https://github.com/retro-tool/retro-tool/issues/61 for the FE

**Review by rudeayelo — APPROVED** [review]
Great job! Love the new toasts 😄

**Comment by uesteibar** [comment]
@marciobarrios can we merge this already? I've merged https://github.com/retro-tool/retro-tool-api/pull/25

**Comment by marciobarrios** [comment]
@uesteibar nope! not yet I still need to add some small tweaks, let me add them and then I'll ping you to test it.

**Comment by marciobarrios** [comment]
@uesteibar Now is ready to review and test. Can you test these situations locally?

- A retro can be password-protected
- If you open a password-protected retro the UI asks for the pass (try also in another browser/tab, the pass is stored in the session)
- A password can be updated (if you try to use the same pass as before the UI should warn you)
- A password can be removed (so the retro is public again)

I think these are the basic cases (would be nice to check at the same time with different browsers/users), also please check the copy. Thanks!

**Comment by uesteibar** [comment]
@marciobarrios it works as expected!

However I experienced the following behavior:

- _User A_ creates the retro and sets password `password`
- _User B_ enters the retro with the correct password
- _User B_ changes the password to `pass`
- _User A_ adds an item. They won't show it updated in the UI, but it will be actually created
- _User A_ refreshes the browser, then it's fine

This is happening because we're actually checking for the password when broadcasting `retroUpdated` subscription events (this was done in https://github.com/retro-tool/retro-tool-api/commit/9894a5d196f3451116cbf9aada3c1d847eaaf506). This can be fixed in two ways:
1. Only checking that the password is correct when the user enters the retro (exactly [this check](https://github.com/retro-tool/retro-tool-api/commit/9894a5d196f3451116cbf9aada3c1d847eaaf506#diff-f9a600fd76d10a05069adadd4fa6e04d0ea0df0b7d2209abd7a5cae542d58dc7R239)). In this case, if the password changes when other users are logged into the retro, then the retro will continue working just fine for them until they refresh, then they'll have to enter the new password.
2. Having a separate `retroPasswordChange` subscription that the FE can subscribe to, so that when an event is received in this channel the page is refreshed, effectively forcing the user to enter the new password.

What do you folks prefer? I'm fine with either. Option 1 only requires BE changes, but leaves that gap in between where users aren't forced to enter the new password until they refresh. Option 2 requires both FE and BE changes.

I also think we can release this _as it is_, even with this corner case, and fix it separately.

cc/ @rudeayelo @atrzaska

**Comment by rudeayelo** [comment]
Hands down option 2, if I change the password I want to effectively "log out" other users.

**Comment by marciobarrios** [comment]
I don't have a strong opinion about it. Both seems fine for me, I don't think this situation will happen often (a user changes pass while other is adding items).

And I agree that we should merge this one and then work on the improvement.

**Comment by uesteibar** [comment]
@rudeayelo what's your take on merging (and releasing) this and fixing separately?

**Comment by rudeayelo** [comment]
> @rudeayelo what's your take on merging (and releasing) this and fixing separately?

No problemo, ship ship

**Comment by uesteibar** [comment]
I added https://github.com/retro-tool/retro-tool/issues/63 and https://github.com/retro-tool/retro-tool/issues/64 to handle this corner case

**Pull request merged**
